language: node_js
  node_js:
    - "node"
  cache: npm
  script: npm run build
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $Git_token
    local_dir: TicketSystemAppDeploy/dist
    on:
      branch: master